//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eta.Client.EtaServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EtaServiceReference.IEtaService")]
    public interface IEtaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtaService/GetTrainings", ReplyAction="http://tempuri.org/IEtaService/GetTrainingsResponse")]
        System.Collections.Generic.List<Eta.Data.Training> GetTrainings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtaService/GetTrainings", ReplyAction="http://tempuri.org/IEtaService/GetTrainingsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Eta.Data.Training>> GetTrainingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtaService/GetReviews", ReplyAction="http://tempuri.org/IEtaService/GetReviewsResponse")]
        System.Collections.Generic.List<Eta.Data.Review> GetReviews(int trainingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtaService/GetReviews", ReplyAction="http://tempuri.org/IEtaService/GetReviewsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Eta.Data.Review>> GetReviewsAsync(int trainingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtaService/AddReview", ReplyAction="http://tempuri.org/IEtaService/AddReviewResponse")]
        void AddReview(Eta.Data.Review review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtaService/AddReview", ReplyAction="http://tempuri.org/IEtaService/AddReviewResponse")]
        System.Threading.Tasks.Task AddReviewAsync(Eta.Data.Review review);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEtaServiceChannel : Eta.Client.EtaServiceReference.IEtaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EtaServiceClient : System.ServiceModel.ClientBase<Eta.Client.EtaServiceReference.IEtaService>, Eta.Client.EtaServiceReference.IEtaService {
        
        public EtaServiceClient() {
        }
        
        public EtaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EtaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Eta.Data.Training> GetTrainings() {
            return base.Channel.GetTrainings();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Eta.Data.Training>> GetTrainingsAsync() {
            return base.Channel.GetTrainingsAsync();
        }
        
        public System.Collections.Generic.List<Eta.Data.Review> GetReviews(int trainingId) {
            return base.Channel.GetReviews(trainingId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Eta.Data.Review>> GetReviewsAsync(int trainingId) {
            return base.Channel.GetReviewsAsync(trainingId);
        }
        
        public void AddReview(Eta.Data.Review review) {
            base.Channel.AddReview(review);
        }
        
        public System.Threading.Tasks.Task AddReviewAsync(Eta.Data.Review review) {
            return base.Channel.AddReviewAsync(review);
        }
    }
}
